(() => {
  const Game = window.CubDep;

  Game.constants3d = {
    WORLD_W: 2048,
    WORLD_H: 64,
    WORLD_D: 2048,
    CHUNK_SIZE: 16,
    CHUNK_RENDER_DISTANCE: 8,
    CHUNK_UNLOAD_DISTANCE: 10,
    CHUNK_START_SYNC_RADIUS: 2,
    CHUNK_WORKER_MAX_PENDING: 8,
    CHUNK_SYNC_GENERATE_BUDGET: 1,
    CHUNK_DECORATE_BUDGET: 1,
    CHUNK_UNLOAD_COLUMN_BUDGET: 2,
    CHUNK_MESH_REBUILD_BUDGET: 3,
    CHUNK_SAVE_BUDGET: 1,
    CAMERA_FAR_CHUNKS: 9,
    PLAYER_HEIGHT: 1.78,
    PLAYER_RADIUS: 0.32,
    EYE_HEIGHT: 1.58,
    GRAVITY: 24,
    WALK_SPEED: 5.2,
    SPRINT_MULTIPLIER: 1.55,
    JUMP_SPEED: 8.0,
    REACH_DISTANCE: 5.2,
    MOUSE_SENSITIVITY: 0.0022,
    MAX_PITCH: Math.PI * 0.47,
  };
})();
